name: package-release
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm install
      - run: npm run build
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Slack Notification Success
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: "Bot"
          SLACK_ICON_EMOJI: ":bell:"
          SLACK_COLOR: "#5cb85c"
          SLACK_TITLE: "Success to Deploy :rocket:"
          SLACK_MESSAGE: ":closed_book: ${{ github.repository }}"
          MSG_MINIMAL: actions url
      - name: Slack Notification Failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: "Bot"
          SLACK_ICON_EMOJI: ":bell:"
          SLACK_COLOR: "#dc143c"
          SLACK_TITLE: "Failure to Deploy :boom:"
          SLACK_MESSAGE: ":closed_book: ${{ github.repository }}"
          MSG_MINIMAL: actions url
